# vim:fileencoding=utf-8:foldmethod=marker

#Fonts
font_family      CaskaydiaMono Nerd Font

#Terminal bell
enable_audio_bell no

#Advanced
allow_remote_control yes
listen_on unix:/tmp/mykitty

#Theme
#include E-Ink.conf
#include e-ink-custom.conf
#include tea-light.conf
#include tea-dark-v1.conf
#include tea-dark-v2.conf
#include tea-dark-v3.conf
include tea-dark.conf

