# vim:fileencoding=utf-8:foldmethod=marker

#Fonts
font_family      CaskaydiaMono Nerd Font

#Terminal bell
enable_audio_bell no

#Advanced
allow_remote_control yes
listen_on unix:/tmp/mykitty

#Theme
include rose-pine-dawn.conf

