# Close input on singular ESC press
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# Toggle exec file
[[manager.prepend_keymap]]
on   = [ "*"]
run  = 'shell -- chmod u$( [[ -x "$0" ]] && echo -x || echo +x ) "$0"'
desc = "Toggle executable"

# mount.yazi plugin
[[manager.prepend_keymap]]
desc = "Open mount menu"
on  = "M"
run = "plugin mount"

# bunny.yazi plugin
[[manager.prepend_keymap]]
desc = "Start bookmark menu"
on = "b"
run = "plugin bunny"

