plugin {
    hyprbars {
        bar_color = rgba(282828e6)
        bar_height = 20
        bar_blur = false
        bar_title_enabled = true
        bar_text_size = 8
        bar_text_font = Jetbrains Mono Nerd Font Mono Bold
        bar_text_align = center
        bar_buttons_alignment = right
        bar_part_of_window = true
        bar_precedence_over_border = false
        bar_padding = 10
        bar_button_padding = 5
        hyprbars-button = rgb(000000), 12, , hyprctl dispatch killactive, rgb(ff0000)
        hyprbars-button = rgb(000000), 12, , hyprctl dispatch fullscreen 1, rgb(0096ff)
        hyprbars-button = rgb(000000), 12, , hyprctl dispatch togglefloating, rgb(ffff00)
    }
}
